apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lKQUtqWG5kdVZyUlY1TUEwR0NTcUdTSWIzRFFFQkN3VUFNQzh4TFRBckJnTlYKQkFNTUpFRmtiV2x6YzJsdmJpQkRiMjUwY205c2JHVnlJRmRsWW1odmIyc2dSR1Z0YnlCRFFUQWVGdzB5TURFeQpNREl3TnpNeE1UZGFGdzB5TVRBeE1ERXdOek14TVRkYU1DOHhMVEFyQmdOVkJBTU1KRUZrYldsemMybHZiaUJECmIyNTBjbTlzYkdWeUlGZGxZbWh2YjJzZ1JHVnRieUJEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU9tbjdpOXRMNjFEbmNJbmNZdG9TSHNUVkdDSnBYMW9tNTRHM2UxMFlRU1A2Yjk0ZDhwcgpuS3NYaitaam92RkY5TXZxOWhPV2JDV29xdXFGdi81S0wyeW9GbGJJc0NWaWt2dVFqTTVoS1ZiNEZCc01pdHFOCkhoMnBVaXpDSmVTNjZVV2pXV2h1ODFTMGRNclZrNjk3YVRScERQRVpDdFI5azJJaldiS1UyejBjYVYvd3NjcVoKTE51Rmk2Q3o5WnVoY1pWaC9YcjV3YThiZVEra0ZVcEE3UExpS3VTZGNJeVFzWUxoRS9YTGxwNGNVYjREMXE1dgpSRis3LzRYbGw2L2l2T2MzUXFVWXFnODdncUEraThPd0lzb2l2ek9kbElSWXZGcTkzVlA0K29mNkRQL0xGTnd1Ck52Z2plbEV5eWhsamhUSW55U3gyQWJtSlk5WWNQQkpBNHEwQ0F3RUFBYU5RTUU0d0hRWURWUjBPQkJZRUZFakIKbFJnekZQQ0xYby9OSTZnR2lHb0VkOFZrTUI4R0ExVWRJd1FZTUJhQUZFakJsUmd6RlBDTFhvL05JNmdHaUdvRQpkOFZrTUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRnJWT3NTY0NlQkhuZ1VwCmNsQlY2TmRKeWplby9jYzE3cHdEYXdXcHFMaExqVkR6VUE1SzBudzloNjM2K1FuSGt0ekFmNjR3V1JtcGhFd1EKWnlBRVpxNGEwYVZnR2pXWERTVWdpc0R6bjd5SXplODN5NzR4cS8rQ0JHVGZ2UEk5RnczcTNwNS9TdCtZWGtCRAoxR2NBWW9OUTBsVkVvR3hla3BTVGdLSWt1SDRkMmtGS2hLRmZWUE9LaEFSNDdJVk5kbHZySEp0b1FwNm5oWHNhCkc1c0hhRFhYTXpNcXAxY2dTRWJ4M2xPeUJCOUM4K3VUVDlLNEJvVXRVK0xRc2laNUlvNDYzWnVzZmgreFRERXQKRm13VFBYejVBK2FEWUFxcHJ3M3dEV0JRMHNqb1E3YlpZZEdzRS9LVWVvTGl4OCtOeVBPTlhKejdtWENTZmFFMgpZQStiQWVZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://webhook-server.webhook-demo.svc/mutating-baseline
  failurePolicy: Ignore
  matchPolicy: Exact
  name: webhook-server.webhook-demo.svc
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lKQUtqWG5kdVZyUlY1TUEwR0NTcUdTSWIzRFFFQkN3VUFNQzh4TFRBckJnTlYKQkFNTUpFRmtiV2x6YzJsdmJpQkRiMjUwY205c2JHVnlJRmRsWW1odmIyc2dSR1Z0YnlCRFFUQWVGdzB5TURFeQpNREl3TnpNeE1UZGFGdzB5TVRBeE1ERXdOek14TVRkYU1DOHhMVEFyQmdOVkJBTU1KRUZrYldsemMybHZiaUJECmIyNTBjbTlzYkdWeUlGZGxZbWh2YjJzZ1JHVnRieUJEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU9tbjdpOXRMNjFEbmNJbmNZdG9TSHNUVkdDSnBYMW9tNTRHM2UxMFlRU1A2Yjk0ZDhwcgpuS3NYaitaam92RkY5TXZxOWhPV2JDV29xdXFGdi81S0wyeW9GbGJJc0NWaWt2dVFqTTVoS1ZiNEZCc01pdHFOCkhoMnBVaXpDSmVTNjZVV2pXV2h1ODFTMGRNclZrNjk3YVRScERQRVpDdFI5azJJaldiS1UyejBjYVYvd3NjcVoKTE51Rmk2Q3o5WnVoY1pWaC9YcjV3YThiZVEra0ZVcEE3UExpS3VTZGNJeVFzWUxoRS9YTGxwNGNVYjREMXE1dgpSRis3LzRYbGw2L2l2T2MzUXFVWXFnODdncUEraThPd0lzb2l2ek9kbElSWXZGcTkzVlA0K29mNkRQL0xGTnd1Ck52Z2plbEV5eWhsamhUSW55U3gyQWJtSlk5WWNQQkpBNHEwQ0F3RUFBYU5RTUU0d0hRWURWUjBPQkJZRUZFakIKbFJnekZQQ0xYby9OSTZnR2lHb0VkOFZrTUI4R0ExVWRJd1FZTUJhQUZFakJsUmd6RlBDTFhvL05JNmdHaUdvRQpkOFZrTUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRnJWT3NTY0NlQkhuZ1VwCmNsQlY2TmRKeWplby9jYzE3cHdEYXdXcHFMaExqVkR6VUE1SzBudzloNjM2K1FuSGt0ekFmNjR3V1JtcGhFd1EKWnlBRVpxNGEwYVZnR2pXWERTVWdpc0R6bjd5SXplODN5NzR4cS8rQ0JHVGZ2UEk5RnczcTNwNS9TdCtZWGtCRAoxR2NBWW9OUTBsVkVvR3hla3BTVGdLSWt1SDRkMmtGS2hLRmZWUE9LaEFSNDdJVk5kbHZySEp0b1FwNm5oWHNhCkc1c0hhRFhYTXpNcXAxY2dTRWJ4M2xPeUJCOUM4K3VUVDlLNEJvVXRVK0xRc2laNUlvNDYzWnVzZmgreFRERXQKRm13VFBYejVBK2FEWUFxcHJ3M3dEV0JRMHNqb1E3YlpZZEdzRS9LVWVvTGl4OCtOeVBPTlhKejdtWENTZmFFMgpZQStiQWVZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://webhook-server.webhook-demo.svc/validatinging-baseline
  failurePolicy: Ignore
  matchPolicy: Exact
  name: webhook-server.webhook-demo.svc
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30